spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          socketFactory:
            port: ${MAIL_PORT_SSL}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
            connectionTimeout: 5000
            timeout: 3000
            writetimeout: 5000
  thymeleaf:
    enable: true

envio:
  email:
    remetente: ${MAIL_USERNAME}
    nomeRemetente: ${MAIL_NOME_REMETENTE}

server:
  port: ${SERVER_PORT}









